# Image tags — CI (platformPipeline / Kaniko) updates on main.
# IMPORTANT: always quote tags — bare hex is parsed as float in YAML.
gateway:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/npd-shop/gateway
    tag: "d03f34e"
    pullPolicy: Always

authService:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/npd-shop/auth-service
    tag: "d03f34e"
    pullPolicy: Always

catalogService:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/npd-shop/catalog-service
    tag: "d03f34e"
    pullPolicy: Always

orderService:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/npd-shop/order-service
    tag: "d03f34e"
    pullPolicy: Always

paymentWorker:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/npd-shop/payment-worker
    tag: "d03f34e"
    pullPolicy: Always

shopWeb:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/npd-shop/shop-web
    tag: "d03f34e"
    pullPolicy: Always
