{{- if .Values.orderService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    {{- include "shop.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  replicas: {{ .Values.orderService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: npd-shop
      app.kubernetes.io/component: order-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: npd-shop
        app.kubernetes.io/component: order-service
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: order-service
          image: "{{ .Values.orderService.image.repository }}:{{ .Values.orderService.image.tag | toString }}"
          imagePullPolicy: {{ .Values.orderService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8003
          env:
            {{- range $k, $v := .Values.orderService.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- include "shop.secretEnv" . | nindent 12 }}
          {{- include "shop.httpProbes" (dict "path" "/health") | nindent 10 }}
          resources:
            {{- toYaml .Values.orderService.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities: { drop: ["ALL"] }
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    {{- include "shop.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  selector:
    app.kubernetes.io/name: npd-shop
    app.kubernetes.io/component: order-service
  ports:
    - name: http
      port: {{ .Values.orderService.service.port }}
      targetPort: http
{{- end }}
