{{- range $name := list "shop-web" "gateway" "auth-service" "catalog-service" "order-service" "payment-worker" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "shop.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
{{- end }}
